[project]
name = "liblocalization_cpp"
version = "0.0.0"
requires-python = ">=3.10, <3.13"
dependencies = []

[build-system]
requires = [
  "setuptools (>=78.1.0,<79.0.0)",
  "wheel (>=0.45.1,<0.46.0)",
  "pybind11 (>=2.13.6,<3.0.0)",
]
build-backend = "setuptools.build_meta"
