services:
  racecar:
    build:
      context: ../../libracecar
      dockerfile: docker/Dockerfile
      args:
        BASE_IMAGE: sebagarc/racecar2
        DOCKER_UID: ${DOCKER_UID:-1000}
        DOCKER_GID: ${DOCKER_GID:-1000}
    image: local/racecar-sim
    entrypoint: /home/dockeruser/racecar_ws/src/liblocalization/docs/build.sh
    volumes:
      - ..:/home/dockeruser/racecar_ws/src/liblocalization
