name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: liblocalization

      - uses: actions/checkout@v4
        with:
          repository: rss2025-4/libracecar
          ref: 883370b86ddc0b35dfd781394ade83fd83b259fe
          path: libracecar
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - run: |
          cd liblocalization/docs
          export DOCKER_UID=$(id -u)
          export DOCKER_GID=$(id -g)
          docker compose run --build racecar

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: liblocalization/docs/build/html
